registrationApp/config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/login')
  get 'users/new'

  resources :users, only: [:new, :create]
  resources :apikeys, only: [:index, :new, :create, :destroy]
  resource :admins, only: [:show, :destroy]
  resources :events, only: [:show]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'tags' => 'tags#index'
      get 'tags/:id' => 'tags#show'
      get 'tags/:tag_id/events' => 'events#index'
      get 'authenticate' => 'authenticates'

      resource :tags, only: [:show, :index]

      resources :creators, only: [:index, :show, :create, :update, :destroy] do
        resources :events, only: [:index]
      end

      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :tags,  only: [:index, :show, :create, :update, :destroy]
      end

    end
  end

end

registrationApp/app/models/apikey.rb
class Apikey < ActiveRecord::Base
  belongs_to :user
  attr_accessor :tmp_user_id

  before_validation { self.key = Array.new(30){rand(36).to_s(36)}.join.upcase }
  before_validation { set_user }
  before_save { self.device = device.downcase }

  def set_user
    if tmp_user_id && User.find_by(id: tmp_user_id)
      self.user_id = tmp_user_id
    end
  end

  validates :device,
            presence: {:message => "mest be entered"},
            length: {maximum: 25 }

  validates :key,
            presence: true,
            uniqueness: true

  validates :user_id,
            presence: true

end

registrationApp/app/controllers/apikeys_controller.rb
class ApikeysController < ApplicationController
  before_action :check_user, only: [:index, :new, :create, :destroy]

  def index
    @user = User.find_by(id: session[:user_id])
  end

  def new
    @apikey = Apikey.new
  end

  def create
    @apikey = Apikey.new(apikey_params)
    @apikey.tmp_user_id = session[:user_id]

    if @apikey.save
      flash[:success] = "APIkey created"
      redirect_to apikeys_path
    else
      render :action => 'new'
    end
  end

  def destroy
    @apikey = Apikey.find_by(id: params[:id])
    if @apikey
      @apikey.destroy
    end
    flash[:danger] = "Apikey was removed"
    redirect_user
  end

  private
  def apikey_params
    params.require(:apikey).permit(:device)
  end
end

registrationApp/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

registrationApp/app/views/apikeys/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "Create APIkey", new_apikey_path, class: "btn btn-default navbar-btn" %>
    <%= link_to "Log out", logout_path, class: "btn btn-default navbar-btn"  %>
    <p class="navbar-text navbar-right">Signed in, handle your keys with respect</p>
  </div>
</nav>

<table class="table table-hover">
  <tr>
    <td><strong>Device</strong></td>
    <td><strong>Key</strong></td>
    <td><strong>Action</strong></td>
  </tr>
  <% @user.apikeys.each do | apikeys | %>
      <tr>
        <td><%= apikeys.device %></td>
        <td><%= apikeys.key %></td>
        <td><%= link_to "Delete key", apikey_path(apikeys.id), method: :delete, data: { confirm: "Are you sure you want to remove this APIkey?" }%></td>
      </tr>
  <% end %>
</table>

registrationApp/app/views/apikeys/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "Go back", apikeys_path, class: "btn btn-default navbar-btn"%>
    <p class="navbar-text navbar-right">Create an APIkey</p>
  </div>
</nav>


<% if @apikey.errors.any? %>
    <div id="alert alert-danger">
      <h2>Something went wrong with the registration</h2>

      <ul>
        <% @apikey.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @apikey do | f |%>
        <p><%= f.label :device_name  %></p>
        <p><%= f.text_field :device, class: "form-control", placeholder: "Device name" %></p>

        <p><%= f.submit "Create", class: "btn btn-primary" %></p>
    <% end %>
  </div>
</div>