registrationApp/config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/login')
  get 'users/new'

  resources :users, only: [:new, :create]
  resources :apikeys, only: [:index, :new, :create, :destroy]
  resource :admins, only: [:show, :destroy]
  resources :events, only: [:show]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'tags' => 'tags#index'
      get 'tags/:id' => 'tags#show'
      get 'tags/:tag_id/events' => 'events#index'
      get 'authenticate' => 'authenticates'

      resource :tags, only: [:show, :index]

      resources :creators, only: [:index, :show, :create, :update, :destroy] do
        resources :events, only: [:index]
      end

      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :tags,  only: [:index, :show, :create, :update, :destroy]
      end

    end
  end

end

registrationApp/app/views/admins/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "Log out", logout_path, class: "btn btn-default navbar-btn"  %>
    <p class="navbar-text navbar-right">Hello ADMIN</p>
  </div>
</nav>

<% @user.each do | users | %>
    <% if users.id != 1%>
        <h1><span class="label label-default"><%= users.username %></span><%= link_to "Remove user", admins_path(id: users.id),
                                                                                              method: :delete, class: "btn btn-link", data: {confirm: "Are you sure you want to remove the user?"}%></h1>
        <table class="table table-hover">
          <tr>
            <td><strong>Device</strong></td>
            <td><strong>Key<stong></td>
            <td><strong>Action</strong></td>
          </tr>
          <% users.apikeys.each do | apikeys | %>
              <tr>
                <td><%= apikeys.device %></td>
                <td><%= apikeys.key %></td>
                <td><%= link_to "Revoke key", apikey_path(apikeys.id), method: :delete, data: { confirm: "Are you sure you want to revoke the device/key?" }%></td>
              </tr>
          <% end %>
        </table>
    <% end %>
<% end %>